language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - wget https://github.com/puli/cli/releases/download/1.0.0-beta10/puli.phar
  - composer self-update
  - composer require php-http/guzzle6-adapter:dev-master
  - composer install
script: vendor/bin/phpunit
