language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer require puli/composer-plugin:^1.0.0@beta puli/repository:^1.0-@beta puli/discovery:^1.0@beta puli/manager:^1.0@beta puli/url-generator:^1.0@beta php-http/guzzle6-adapter:dev-master
  - composer install
script: vendor/bin/phpunit
