language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer require php-http/guzzle6-adapter:dev-master
  - composer require php-http/httplug:v1.0.0-beta,
  - composer install
script: vendor/bin/phpunit
